use_frameworks!
platform :ios, '13.0'
inhibit_all_warnings!

target 'DeepLinkKit_Example' do
  pod 'SwiftLint'
  pod 'DeepLinkKit/Debug', :path => '../', :testspecs => ['Tests']

  target 'DeepLinkKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'DeepLinkKit-Unit-Debug-Tests'
        config.build_settings['TEST_TARGET_NAME'] = 'DeepLinkKit_Example'
      end
    end
  end
end
